### ISSUE TITLE
clash --init

### ISSUE THREAD

**Issue by parkr** [imathis/clash#11]
Hey!

I was just building out Jekyll textile converter and wanted to use clash to run the integration tests, but I'm a little confused on where the configuration should live and when the configuration supersedes the args passed to `clash`, etc.

Rspec has `rspec --init` which creates `spec/spec_helper.rb` and `.rspec`. You know you're all set to write specs from then on out. Maybe a similar feature?

**Comment by imathis** [comment]
That sounds like a good idea.

Right now the pattern I'm following is this:

```
.clash.yml #at gem root
tests/        # Jekyll test site.
```

Then to run tests I do `bundle exec clash test` which tells it to use the clash config from the current directory and change directories (using the ruby cd block) into `test` before running. So it acts as if it is being run in the tests directory.

**Comment by parkr** [comment]
What's the structure of `test/`? Is it meant to be one site? Is it meant to be a series of sites with their embedded `_expected` dirs?

**Comment by imathis** [comment]
Sheesh, my mind was out the window.


#### Simple version:
Directory structure

```
.clash.yml
test/
  _expected # a copy of what you expect from _site
  _site
  index.html
```

Clash config file:

```yaml
title: Simple build test
build: true
compare: _expected _site
```

#### Test a single part of a build

```
.clash.yml
test/
  _expected # a copy of what you expect from _site/some-feature/
  _site
  some-feature/
    textile-test.textile
    html-test.html
    markdown-test.md
```

Clash config file:

```yaml
title: Simple build test
build: true
compare: _expected/some_feature _site/some_feature
```

Does that make more sense?

**Comment by imathis** [comment]
I'll add you can use the second method to test multiple features with a single build. So you could do this.

Clash config file:

```yaml
-
title: Simple build
build: true
-
title: Test Feature 1
compare: _expected/feature1 _site/feature1
-
title: Test Feature 2
compare: _expected/feature2 _site/feature2
```

You can also just compare individual files, but often a single test uses multiple files, so I typically compare directories.
